Update to allow NO_CR

diff --git a/.github/workflows/commit_message_checker.yml b/.github/workflows/commit_message_checker.yml
--- a/.github/workflows/commit_message_checker.yml
+++ b/.github/workflows/commit_message_checker.yml
@@ -13,7 +13,16 @@ jobs:
       - name: Validate Squash Commit Message (PR Title)
         run: |
           pr_title="${{ github.event.pull_request.title }}"
-          if ! [[ "$pr_title" =~ ^[^\n]{1,50}$ && "$pr_title" =~ SCRUM[0-9]+ ]]; then
-            echo "Invalid PR title for squash commit: $pr_title"
-            exit 1
+          if [[ "$pr_title" =~ NO_CR ]]; then
+            if ! [[ "$pr_title" =~ ^[^\n]{1,50}$ ]]; then
+              echo "Invalid PR title for squash commit: $pr_title"
+              echo "Expected: Single line, max 50 characters. 'NO_CR' present, so SCRUM code not required."
+              exit 1
+            fi
+          else
+            if ! [[ "$pr_title" =~ ^[^\n]{1,50}$ && "$pr_title" =~ SCRUM[0-9]+ ]]; then
+              echo "Invalid PR title for squash commit: $pr_title"
+              echo "Expected: Single line, max 50 characters, must include 'SCRUM' followed by digits (e.g., 'SCRUM123: short description'), or 'NO_CR' if no SCRUM code applies."
+              exit 1
+            fi
           fi
